# gitlab-ci

image: docker:stable

stages:
  - package
  - docker_build

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

package:
  image: maven:3.5.4-jdk-8-alpine
  stage: package
  script:
    - mvn package

docker_build:
  image: opspresso/builder:v0.7.69
  stage: docker_build
  script:
    - docker build -f Dockerfile -t $IMAGE_TAG .
