server:
  port: 8080

spring:
  application:
    name: sample-spring
  profiles:
    active: ${PROFILE:default}
  jackson:
    time-zone: Asia/Seoul
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

namespace: ${NAMESPACE:default}

message: ${MESSAGE:Refreshed}

version: ${VERSION:v0.0.0}

slack:
  webhook: ${SLACK_WEBHOOK:/slack/token}
  channel: ${SLACK_CHANNEL:sandbox}

opentracing:
  jaeger:
    enable-b3-propagation: true
    # http-sender:
    #   url: ${JAEGER_HTTP_SENDER_URL}
    udp-sender:
      host: ${JAEGER_UDP_SENDER_HOST:localhost}
      port: ${JAEGER_UDP_SENDER_PORT:6831}

task:
  scheduled: ${TASK_SCHEDULED:false}

---
spring:
  profiles: default
message: ":tada: Server UP"

---
spring:
  profiles: dev
message: ":tada: Development UP"

---
spring:
  profiles: stage
message: ":tada: Staging UP"

---
spring:
  profiles: prod
message: ":tada: Production UP"
