server:
  port: 8080

spring:
  application:
    name: sample-spring
  profiles:
    active: ${PROFILE:default}
  jackson:
    time-zone: Asia/Seoul
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

namespace: ${NAMESPACE:default}

message: ${MESSAGE:Refreshed}

version: ${VERSION:v0.0.0}

slack:
  webhook: ${SLACK_WEBHOOK:/slack/token}
  channel: ${SLACK_CHANNEL:sandbox}

---
spring:
  profiles: default
message: ":tada: Server UP"

---
spring:
  profiles: dev
message: ":tada: Development UP"

---
spring:
  profiles: stage
message: ":tada: Staging UP"

---
spring:
  profiles: prod
message: ":tada: Production UP"
