server:
  port: 8080

spring:
  application:
    name: sample-spring
  profiles:
    active: ${PROFILE:default}
  jackson:
    time-zone: Asia/Seoul
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

namespace: ${NAMESPACE:default}

version: ${VERSION:v0.0.0}

slack:
  webhook: ${SLACK_WEBHOOK:/slack/token}
  channel: ${SLACK_CHANNEL:sandbox}

message: ${MESSAGE:Refreshed}

aws:
  region: ${AWS_REGION:ap-northeast-2}
  key:
    access: ${AWS_ACCESS_KEY:STRING}
    secret: ${AWS_SECRET_KEY:STRING}
  sqs:
    queueName: sample
    maxTimeout: ${AWS_SQS_MAX_TIMEOUT:36000}
    maxDelay: ${AWS_SQS_MAX_DELAY:900}
    endPoint: sqs.${AWS_REGION:ap-northeast-2}.amazonaws.com

logzio:
  token: ${LOGZIO_TOKEN:STRING}

---
spring:
  profiles: default
message: ":tada: Server UP"

---
spring:
  profiles: dev
  jmx:
    unique-names: true
management:
  endpoints:
    jmx:
      domain: com.nalbam.sample
message: ":tada: Development UP"

---
spring:
  profiles: stage
message: ":tada: Staging UP"

---
spring:
  profiles: prod
message: ":tada: Production UP"
