fullnameOverride: sample-spring

replicaCount: 1

profile: default

namespace: development

image:
  repository: docker-registry.127.0.0.1.nip.io:30500/sample-spring
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
  annotations: {}
  labels: {}

ingress:
  enabled: true
  subdomain: sample-spring
  basedomain: 127.0.0.1.nip.io

autoscaling:
  enabled: false

resources:
  requests:
    cpu: 250m
    memory: 1024Mi
  limits:
    cpu: 300m
    memory: 1252Mi

readinessProbe:
  httpGet:
    path: /
    port: 8080
  initialDelaySeconds: 60
  periodSeconds: 10
  failureThreshold: 3

livenessProbe:
  httpGet:
    path: /
    port: 8080
  initialDelaySeconds: 60
  periodSeconds: 10
  failureThreshold: 3

env:
  - name: MESSAGE
    value: "hello local world"

configmap:
  enabled: false

secret:
  enabled: false
